# $OpenBSD$

COMMENT=		visual binary diff

DISTNAME=		vbindiff-3.0_beta5
PKGNAME=    		vbindiff-3.0-beta5
EXTRACT_SUFX= 		.tar.gz
WRKDIST=		${WRKDIR}/vbindiff-3.0_beta5

CATEGORIES=		editors

HOMEPAGE=		http://www.cjmweb.net/vbindiff/

# GPLv2+
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB += 		c m ncurses panel stdc++

MASTER_SITES = 		http://www.cjmweb.net/vbindiff/

CONFIGURE_STYLE= 	gnu

.include <bsd.port.mk>
