# $OpenBSD$

COMMENT =		backup a github user or organization

MODPY_EGG_VERSION =	0.20.0
DISTNAME =		github-backup-${MODPY_EGG_VERSION}
PKGNAME =		github-backup-${MODPY_EGG_VERSION}
CATEGORIES =   		devel

HOMEPAGE =		https://github.com/josegonzalez/python-github-backup

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =		python3
FLAVOR ?=

.include <bsd.port.mk>
