# $$

COMMENT =		Python library for Intel HEX files manipulations

MODPY_EGG_VERSION = 	2.3.0
DISTNAME =		py-intelhex-${MODPY_EGG_VERSION}

GH_ACCOUNT =		python-intelhex
GH_PROJECT =		intelhex
GH_TAGNAME =		${MODPY_EGG_VERSION}

CATEGORIES =		devel

MAINTAINER =		Ralf Horstmann <ralf+github@ackstorm.de>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
