# $OpenBSD:$

COMMENT =		Access CP/M file systems similar to mtools
DISTNAME =		cpmtools-2.23

CATEGORIES =		sysutils

HOMEPAGE =		http://www.moria.de/~michael/cpmtools/

MAINTAINER =		Ralf Horstmann <ralf+ports@ackstorm.de>

# GPLv2+
PERMIT_DISTFILES =	Yes
PERMIT_PACKAGE =	Yes

WANTLIB = c

SITES =			http://www.moria.de/~michael/cpmtools/files/

CONFIGURE_STYLE =	gnu


.include <bsd.port.mk>
