# $OpenBSD$

COMMENT=		AS is a portable macro cross assembler

PKGNAME=		asl-1.42.194
DISTNAME=		asl-current
DISTFILES=		asl-current-142-bld194.tar.bz2

CATEGORIES=		devel

HOMEPAGE=		http://john.ccac.rwth-aachen.de:8000/as/
MASTER_SITES=		http://john.ccac.rwth-aachen.de:8000/ftp/as/source/c_version/

# GPLv2/GPLv3
PERMIT_PACKAGE=		Yes

WANTLIB += 		c

USE_GMAKE=		Yes


.include <bsd.port.mk>
