# $OpenBSD$

COMMENT=		AS is a portable macro cross assembler

BUILD=			273
PKGNAME=		asl-1.42.$(BUILD)
DISTNAME=		asl-current
DISTFILES=		asl-current-142-bld$(BUILD).tar.bz2

CATEGORIES=		devel

HOMEPAGE=		http://john.ccac.rwth-aachen.de:8000/as/
SITES=			http://john.ccac.rwth-aachen.de:8000/ftp/as/source/c_version/

# GPLv2/GPLv3
PERMIT_PACKAGE=		Yes

WANTLIB += 		c

USE_GMAKE=		Yes


.include <bsd.port.mk>
