# $OpenBSD:$

COMMENT =		C-like compiler that translates to HP48 RPL
DISTNAME =		hp48cc-1.3

CATEGORIES =		devel

HOMEPAGE =		http://www.sigala.it/sandro/download.php

MAINTAINER =		Ralf Horstmann <ralf+ports@ackstorm.de>

# GPLv2+
PERMIT_DISTFILES =	Yes
PERMIT_PACKAGE =	Yes

WANTLIB = c

MASTER_SITES =		http://www.sigala.it/sandro/files/

CONFIGURE_STYLE =	gnu


.include <bsd.port.mk>
